### PR TITLE
0.10.1 h76b996

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/camelot-py-feedstock/pull/22

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
The dependencies might be a little overkill @vinayak-mehta can you take a look?

**Comment by izahn** [comment]
Otherwise I think this is ready to be merged

**Comment by vinayak-mehta** [comment]
I'll take a look today!

**Comment by izahn** [comment]
If you have a chance to take a look this weekend that would be great!

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
If you don't have time for a full review this is probably safe to merge as-is. 0.9 is giving me trouble along the lines of https://github.com/camelot-dev/camelot/issues/234, hoping 0.10 works better.

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
I think this is ready to be merged.

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
Ready to merge @vinayak-mehta

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
@conda-forge/core there has been no response from the maintainer here since the end of May. If you have time to review and merge this update I would appreciate it!

**Pull request merged**
