### PR TITLE
update to 0.7.2

### PR DESCRIPTION
**Pull request by pvanheus**
* update pdfminer.six dependency to capture the version with python 3.7 support

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pvanheus** [comment]
@conda-forge-admin, please rerender

**Comment by pvanheus** [comment]
The build is failing because it (or, I suspect, OpenCV) depends  on `libGL.so.1` which is something provided along with a specific graphics driver.

**Comment by vinayak-mehta** [comment]
Hey @pvanheus, sorry for being inactive here. Let me look into this on Sunday.

**Comment by pvanheus** [comment]
@conda-forge-admin, please rerender

**Comment by pvanheus** [comment]
@conda-forge-admin, please rerender

> Hey @pvanheus, sorry for being inactive here. Let me look into this on Sunday.

No worries, thanks for the awesome `camelot-py` package.

**Comment by vinayak-mehta** [comment]
All checks have passed! Should I merge this? Though I'm not sure about the changes that you did. Will review them first, would help if you can give a small summary :)

**Comment by pvanheus** [comment]
> All checks have passed! Should I merge this? Though I'm not sure about the changes that you did. Will review them first, would help if you can give a small summary :)

1. I updated the `pdfminer.six` package and made that `noarch`. This dependency was causing problems for `camelot-py`.
2. I changed the build line to the recommended `pip` based installation method and added `pip` as a `host` requirement.
3. I added a `yum_requirements.txt` file that specified `mesa-libGL` as a dependency so that the tests pass.
4. I asked for a re-render. This is actually the step that led to the majority of the changes in this PR (done by the re-render bot).

**Comment by pvanheus** [comment]
@vinayak-mehta given the summary above, can you perhaps merge this PR or is there more that you would like to review / discuss?

**Comment by vinayak-mehta** [comment]
Merged. Thanks for the changes!

**Pull request merged**
