### PR TITLE
MNT: Add noarch: python

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've made the recipe `noarch: python` as instructed in #16.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by vinayak-mehta** [comment]
@conda-forge-admin, please rerender

**Comment by vinayak-mehta** [comment]
> noarch packages can't have selectors. If the selectors are necessary, please remove noarch: python.

Does the linter refer to `# [not win]`? Since ghostscript is now available for Windows (https://github.com/conda-forge/ghostscript-feedstock/issues/5), I could try removing this selector.

**Comment by vinayak-mehta** [comment]
@conda-forge-admin, please rerender

**Comment by vinayak-mehta** [comment]
@mariusvniekerk Please correct me if I'm wrong. `noarch: python` makes sure that the package will only be built once, linux in this case. But the package will work on macos and windows too, right?

**Comment by mariusvniekerk** [comment]
Since this is a pure python library with no platform specific dependencies and no python version depending deps, we can use this mode.

This will work on all platforms (including things like aarch64)

**Comment by vinayak-mehta** [comment]
Thanks for the clarification! Merging this PR.

**Pull request merged**
