### PR TITLE
reissue py38 migration

### PR DESCRIPTION
**Pull request by mariusvniekerk**

### CODE REVIEW

**Review by vinayak-mehta — COMMENTED** [review]
@mariusvniekerk I haven't tested the package on Python 3.8 yet.  Is it possible to do this update at a later time?

**Comment by vinayak-mehta** [comment]
@conda-forge-admin, please rerender

**Comment by vinayak-mehta** [comment]
@mariusvniekerk The windows build was failing initially, I think it was because of `updateConda: false`. The render fixed this, but removed builds for different Python versions from the matrix. Is that expected behavior? Or should I make the matrix the same as before?

**Comment by mariusvniekerk** [comment]
That is expected behavior. Conda forge no longer builds py27 packages

**Comment by vinayak-mehta** [comment]
@mariusvniekerk Thanks for your reply. My query is around the removal of matrix jobs for Python 3 versions https://github.com/conda-forge/camelot-py-feedstock/pull/14/files#diff-7444b123ae5ae1c0f142ddeaa65cc392R10 after the rerender.

Also, I see that the linux build was canceled, let me see if I can re-run it.

**Comment by vinayak-mehta** [comment]
@conda-forge-admin, please restart ci

**Pull request merged**
